# Generated by Django 6.0.5 on 2026-05-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
                ('significado', models.TextField()),
                ('exemplo', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(default='pt-br', max_length=5)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'palavras',
            },
        ),
    ]
